version: "3"

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  django:
    build:
      context: .
      args:
        DJANGO_ENV: development
    command: python -Wd manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    depends_on:
      - postgres
